# Generated by Django 4.2.2 on 2023-08-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
        ),
    ]
