# Generated by Django 4.2.2 on 2023-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0002_alter_student_profile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(default='CSE', max_length=100)),
            ],
            options={
                'db_table': 'Student_data',
            },
        ),
        migrations.DeleteModel(
            name='Student_profile',
        ),
    ]
