# Generated by Django 4.2.2 on 2023-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0005_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='s_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
