# Generated by Django 4.2.2 on 2023-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0008_alter_faculty_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(),
        ),
    ]
