# Generated by Django 4.2.2 on 2023-08-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0010_faculty1_delete_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty1',
            new_name='Faculty_list',
        ),
    ]
