# Generated by Django 4.2.2 on 2023-08-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0012_faculty_delete_faculty_list'),
    ]

    operations = [
    ]
