# Generated by Django 4.2.2 on 2023-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0013_auto_20230803_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='faculty_excel/'),
        ),
    ]
