# Generated by Django 4.2.2 on 2023-08-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0014_faculty_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
