# Generated by Django 4.2.2 on 2023-08-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0017_mappedexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFacultyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_registration_number', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('student_branch', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=254)),
                ('faculty_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MappedExcel',
        ),
    ]
