# Generated by Django 4.2.2 on 2023-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0018_studentfacultymapping_delete_mappedexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_report', models.FileField(upload_to='uploads/')),
                ('certificate', models.FileField(upload_to='uploads/')),
                ('ppt', models.FileField(upload_to='uploads/')),
                ('final_project_report', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
