# Generated by Django 4.2.2 on 2023-09-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern_Portal', '0020_myuploadedfiles_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadedfiles',
            name='faculty',
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='faculty_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
