# Generated by Django 4.2.2 on 2023-09-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Intern_Portal', '0021_remove_myuploadedfiles_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadedfiles',
            name='faculty_name',
        ),
        migrations.AddField(
            model_name='myuploadedfiles',
            name='faculty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
